spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
server:
  port: 8089